In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('train.csv')
l=dataset.iloc[:,[5]].values
r=l.size

In [2]:
temp=0
for i in range(r):
    if l[i]>-1:
        temp+=l[i]
    else:
        continue        

C:\Users\atchay\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in greater
  This is separate from the ipykernel package so we can avoid doing imports until


In [3]:
temp

array([21205.17])

In [4]:
rr=temp//892
rr

array([23.])

In [5]:
for i in range(r):
    if l[i]>-1:
        continue
    else:
        l[i]=rr

C:\Users\atchay\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in greater
  


In [6]:
X = dataset.iloc[:,[0,2]].values
#y = dataset.iloc[:,1].values
#X[:,2]=l
X.shape

(891, 2)

In [7]:
l.ravel().shape

(891,)

In [8]:
X_final=np.zeros((891,3))
X_final[:,0:2]=X
X_final[:,2]=l.ravel()
X_final

array([[  1.,   3.,  22.],
       [  2.,   1.,  38.],
       [  3.,   3.,  26.],
       ...,
       [889.,   3.,  23.],
       [890.,   1.,  26.],
       [891.,   3.,  32.]])

In [9]:

y = dataset.iloc[:, 1].values
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size = 0.25, random_state = 42)


C:\Users\atchay\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [10]:
import _pickle as pickle

In [11]:
from xgboost import XGBClassifier

In [12]:
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [14]:
pickle.dump(model,open('xgboost.pkl', 'wb'))

In [18]:
y_pred = model.predict(X_test)

C:\Users\atchay\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [19]:
from sklearn import metrics
metrics.accuracy_score(y_pred, y_test)

0.7174887892376681

In [20]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [21]:
cm

array([[113,  21],
       [ 42,  47]], dtype=int64)